### ISSUE TITLE
Tickets auto creation

### ISSUE THREAD

**Issue by iOwlet** [getsentry/sentry-jira#88]
Hello!
I use getsentry.com service with jira integration 0.11.0.dev0. 
I can mannually create tickets (all settings are right), but tickets auto creation doesn't work (I check Auto create JIRA tickets almost). Can you help me?

**Comment by helloszabi** [comment]
Hi,

we've got the same problem here with an on-premise Sentry + sentry-jira 0.11.0.dev0

We've are using a dedicated Jira user for Sentry which is in a group with the following permissions:
- Browse Projects
- Assign Issues
- Create Issues
- Browse Users (Administartion » System » Global permissions) 

We have Crashlytics also in this group and that user is working fine. But somehow Sentry can't create tickets automatically. Interestingly the "Create Jira ticket" button on an issue page is working and creating the tickets.

We have dozens of projects, and we have enabled and of course set up Jira integration in all of them, so that would not be a problem, and it was one week ago now.

Another interesting problem is that today, for the first time, Sentry created an internal issue with the following data:

``` json
{  
  "id":"de0cd83806c9486ead65c8e0aacd4a76",
  "project":1,
  "release":null,
  "platform":"python",
  "culprit":"root in error",
  "message":"Error creating JIRA ticket: {u'project': [u'project is required'], '__all__': [[]]}",
  "datetime":"2016-05-05T11:20:35.000000Z",
  "time_spent":null,
  "tags":[  
    [  
      "project",
      "6"
    ],
    [  
      "transaction_id",
      "None"
    ],
    [  
      "task_name",
      "sentry.tasks.post_process.plugin_post_process_group"
    ],
    [  
      "site",
      "example.com"
    ],
    [  
      "level",
      "error"
    ],
    [  
      "logger",
      "root"
    ],
    [  
      "server_name",
      "sentry"
    ]
  ],
  "errors":[  

  ],
  "extra":{  
    "thread":140388546332416,
    "process":9066,
    "sys.argv":[  
      "'/data/sentry/bin/sentry'",
      "'celery'",
      "'worker'",
      "'-l'",
      "'WARNING'"
    ],
    "threadName":"'MainThread'",
    "filename":"'__init__.pyc'",
    "processName":"'Worker-2'",
    "pathname":"'/usr/lib/python2.7/logging/__init__.pyc'",
    "lineno":1178,
    "asctime":"'2016-05-05 11:20:35,548'"
  },
  "fingerprint":[  
    "{{ default }}"
  ],
  "modules":{  
    "python":"2.7.9",
    "sentry":"8.4.0"
  },
  "received":1462447235.0,
  "sdk":{  
    "version":"5.15.0",
    "name":"raven-python"
  },
  "sentry.interfaces.Message":{  
    "message":"Error creating JIRA ticket: {u'project': [u'project is required'], '__all__': [[]]}"
  },
  "type":"default",
  "version":"5"
}
```

Do you have any idea what could cause the problem, or how we could debug it?

Thanks,
Szabolcs

**Comment by iOwlet** [comment]
Hi, Szabolcs!
Could you tell me, how to see internal issues, which Sentry created?
Thanks,
Yulia

**Comment by helloszabi** [comment]
If you don't see them on your Dashboard, then you're not in the Sentry team.

Check here: Projects & Teams » All Teams » Sentry - if you see the Leave Team button, then you're in.
Then go to Projects & Teams again and click on Sentry » Internal

**Comment by mindojo-victor** [comment]
Same here. Going back to 0.10 makes it work:

```
pip install git+https://github.com/getsentry/sentry-jira.git@0.10.0
```

**Comment by helloszabi** [comment]
Thanks, we'll try the downgrade, I'll let you know the results.

**Comment by dcramer** [comment]
Honestly, I'm very tempted to remove the auto creation functionality. It's very complex (because Jira), and it's not the intended way to use Sentry. We're not a data processing tool, we're a workflow tool, and Jira cripples that workflow when you try to just auto create tickets from everything.

**Comment by thurloat** [comment]
I totally agree David, doesn't fit my sentry work flow either.

I can imagine that auto creating jira tickets ends with the ticket triage
folks on one's team working overtime to clean up bad tickets with no
context.

**Comment by dcramer** [comment]
I'm going to be removing auto_create form Jira as it doesn't make sense in Sentry in the current form, and it causes way too much confusion.

**Comment by danheberden** [comment]
@dcramer fyi the checkbox is still there for this removed feature

**Comment by homerovalle** [comment]
👍  @danheberden

**Comment by dcramer** [comment]
We're going to be overhauling the Jira plugin soon as part of our ongoing effort to improve this part of the ecosystem. Will make sure we take care of the auto creation issues at that time as well.

**Comment by PXke** [comment]
I don't really understand why you would like to delete the auto creation issue. 

In our current system we have a dev project that is not connected with this plugin, but we have prod one with the plugin activated with auto create tickets. In Jira we have a special dedicated "Hardening" project where the tasks are created. 

Because all errors are important in production I think it makes sense.

**Comment by dcramer** [comment]
@PXke because quite frankly its a bad idea. If you get a large burst of exceptions, the last thing you want is your JIRA to be flooded with those.

**Comment by danheberden** [comment]
@PXke We had a long talk about this in our teams as well at Bazaarvoice. We found anything severe enough to trigger "Get up now and fix this" type of alerts would work with data funneled to datadog, and ultimately pagerduty. For most cases, reviewing the exceptions daily to either trigger making a ticket for one/multiple issues or reviewing the exceptions daily during standup made for a better workflow.

**Comment by shahp00ja** [comment]
@dcramer apologies for hijacking the thread however, is this feature available for GitHub now ?
https://forum.sentry.io/t/way-to-automatically-raise-github-issue-from-sentry-web/876

**Comment by p00j4** [comment]
@dcramer apologies for hijacking the thread however, is this feature available for GitHub now ?
https://forum.sentry.io/t/way-to-automatically-raise-github-issue-from-sentry-web/876
